# Form implementation generated from reading ui file 'c:\Users\FabianSchÃ¶pflin\sources\DBREF\InfraLRS\lrs\ui\ui_lrsdockwidget.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtWidgets


class Ui_LrsDockWidget(object):
    def setupUi(self, LrsDockWidget):
        LrsDockWidget.setObjectName("LrsDockWidget")
        LrsDockWidget.resize(739, 754)
        self.dockWidgetContents = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.dockWidgetContents.sizePolicy().hasHeightForWidth()
        )
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.dockWidgetContents)
        self.tabWidget.setObjectName("tabWidget")
        self.locateTab = QtWidgets.QWidget()
        self.locateTab.setObjectName("locateTab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.locateTab)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.locateLrsRouteFieldLabel = QtWidgets.QLabel(parent=self.locateTab)
        self.locateLrsRouteFieldLabel.setObjectName("locateLrsRouteFieldLabel")
        self.gridLayout_3.addWidget(self.locateLrsRouteFieldLabel, 1, 0, 1, 1)
        self.locateRouteCombo = QtWidgets.QComboBox(parent=self.locateTab)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.locateRouteCombo.sizePolicy().hasHeightForWidth()
        )
        self.locateRouteCombo.setSizePolicy(sizePolicy)
        self.locateRouteCombo.setObjectName("locateRouteCombo")
        self.gridLayout_3.addWidget(self.locateRouteCombo, 7, 1, 1, 1)
        self.locateLrsLayerCombo = QtWidgets.QComboBox(parent=self.locateTab)
        self.locateLrsLayerCombo.setObjectName("locateLrsLayerCombo")
        self.gridLayout_3.addWidget(self.locateLrsLayerCombo, 0, 1, 1, 1)
        self.locateCoordinates = QtWidgets.QLabel(parent=self.locateTab)
        self.locateCoordinates.setTextInteractionFlags(
            QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse
            | QtCore.Qt.TextInteractionFlag.TextSelectableByMouse
        )
        self.locateCoordinates.setObjectName("locateCoordinates")
        self.gridLayout_3.addWidget(self.locateCoordinates, 10, 1, 1, 1)
        self.line_6 = QtWidgets.QFrame(parent=self.locateTab)
        self.line_6.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_3.addWidget(self.line_6, 11, 0, 1, 2)
        self.locateHighlightCheckBox = QtWidgets.QCheckBox(parent=self.locateTab)
        self.locateHighlightCheckBox.setText("")
        self.locateHighlightCheckBox.setChecked(True)
        self.locateHighlightCheckBox.setObjectName("locateHighlightCheckBox")
        self.gridLayout_3.addWidget(self.locateHighlightCheckBox, 12, 1, 1, 1)
        self.locateCoordinatesLabel = QtWidgets.QLabel(parent=self.locateTab)
        self.locateCoordinatesLabel.setObjectName("locateCoordinatesLabel")
        self.gridLayout_3.addWidget(self.locateCoordinatesLabel, 10, 0, 1, 1)
        self.locateMeasureLabel = QtWidgets.QLabel(parent=self.locateTab)
        self.locateMeasureLabel.setObjectName("locateMeasureLabel")
        self.gridLayout_3.addWidget(self.locateMeasureLabel, 9, 0, 1, 1)
        self.locateMeasureSpin = QtWidgets.QDoubleSpinBox(parent=self.locateTab)
        self.locateMeasureSpin.setDecimals(6)
        self.locateMeasureSpin.setMaximum(1000000.0)
        self.locateMeasureSpin.setSingleStep(1.0)
        self.locateMeasureSpin.setObjectName("locateMeasureSpin")
        self.gridLayout_3.addWidget(self.locateMeasureSpin, 9, 1, 1, 1)
        self.locateBufferSpin = QtWidgets.QDoubleSpinBox(parent=self.locateTab)
        self.locateBufferSpin.setDecimals(6)
        self.locateBufferSpin.setMaximum(1000000.0)
        self.locateBufferSpin.setSingleStep(50.0)
        self.locateBufferSpin.setProperty("value", 200.0)
        self.locateBufferSpin.setObjectName("locateBufferSpin")
        self.gridLayout_3.addWidget(self.locateBufferSpin, 13, 1, 1, 1)
        self.locateRanges = QtWidgets.QLabel(parent=self.locateTab)
        self.locateRanges.setWordWrap(True)
        self.locateRanges.setTextInteractionFlags(
            QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse
            | QtCore.Qt.TextInteractionFlag.TextSelectableByMouse
        )
        self.locateRanges.setObjectName("locateRanges")
        self.gridLayout_3.addWidget(self.locateRanges, 8, 1, 1, 1)
        self.locateLrsLayerLabel = QtWidgets.QLabel(parent=self.locateTab)
        self.locateLrsLayerLabel.setObjectName("locateLrsLayerLabel")
        self.gridLayout_3.addWidget(self.locateLrsLayerLabel, 0, 0, 1, 1)
        self.locateLrsRouteFieldCombo = QtWidgets.QComboBox(parent=self.locateTab)
        self.locateLrsRouteFieldCombo.setObjectName("locateLrsRouteFieldCombo")
        self.gridLayout_3.addWidget(self.locateLrsRouteFieldCombo, 1, 1, 1, 1)
        self.line_7 = QtWidgets.QFrame(parent=self.locateTab)
        self.line_7.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_3.addWidget(self.line_7, 5, 0, 1, 2)
        self.locateRouteLabel = QtWidgets.QLabel(parent=self.locateTab)
        self.locateRouteLabel.setObjectName("locateRouteLabel")
        self.gridLayout_3.addWidget(self.locateRouteLabel, 7, 0, 1, 1)
        self.locateRangesLabel = QtWidgets.QLabel(parent=self.locateTab)
        self.locateRangesLabel.setObjectName("locateRangesLabel")
        self.gridLayout_3.addWidget(self.locateRangesLabel, 8, 0, 1, 1)
        self.locateBufferLabel = QtWidgets.QLabel(parent=self.locateTab)
        self.locateBufferLabel.setObjectName("locateBufferLabel")
        self.gridLayout_3.addWidget(self.locateBufferLabel, 13, 0, 1, 1)
        self.locateHighlightLabel = QtWidgets.QLabel(parent=self.locateTab)
        self.locateHighlightLabel.setObjectName("locateHighlightLabel")
        self.gridLayout_3.addWidget(self.locateHighlightLabel, 12, 0, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.locateHelpButton = QtWidgets.QPushButton(parent=self.locateTab)
        self.locateHelpButton.setObjectName("locateHelpButton")
        self.horizontalLayout_5.addWidget(self.locateHelpButton)
        self.locateCenterButton = QtWidgets.QPushButton(parent=self.locateTab)
        self.locateCenterButton.setObjectName("locateCenterButton")
        self.horizontalLayout_5.addWidget(self.locateCenterButton)
        self.locateZoomButton = QtWidgets.QPushButton(parent=self.locateTab)
        self.locateZoomButton.setObjectName("locateZoomButton")
        self.horizontalLayout_5.addWidget(self.locateZoomButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.locateProgressBar = QtWidgets.QProgressBar(parent=self.locateTab)
        self.locateProgressBar.setProperty("value", 24)
        self.locateProgressBar.setObjectName("locateProgressBar")
        self.verticalLayout_8.addWidget(self.locateProgressBar)
        spacerItem = QtWidgets.QSpacerItem(
            20,
            193,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.verticalLayout_8.addItem(spacerItem)
        self.tabWidget.addTab(self.locateTab, "")
        self.eventsTab = QtWidgets.QWidget()
        self.eventsTab.setObjectName("eventsTab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.eventsTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.eventsGridLayout = QtWidgets.QGridLayout()
        self.eventsGridLayout.setObjectName("eventsGridLayout")
        self.eventsMeasureEndFieldLabel = QtWidgets.QLabel(parent=self.eventsTab)
        self.eventsMeasureEndFieldLabel.setObjectName("eventsMeasureEndFieldLabel")
        self.eventsGridLayout.addWidget(self.eventsMeasureEndFieldLabel, 10, 0, 1, 1)
        self.eventsLrsRouteFieldCombo = QtWidgets.QComboBox(parent=self.eventsTab)
        self.eventsLrsRouteFieldCombo.setObjectName("eventsLrsRouteFieldCombo")
        self.eventsGridLayout.addWidget(self.eventsLrsRouteFieldCombo, 4, 1, 1, 1)
        self.eventsErrorFieldLineEdit = QtWidgets.QLineEdit(parent=self.eventsTab)
        self.eventsErrorFieldLineEdit.setObjectName("eventsErrorFieldLineEdit")
        self.eventsGridLayout.addWidget(self.eventsErrorFieldLineEdit, 15, 1, 1, 1)
        self.eventsOutputNameLineEdit = QtWidgets.QLineEdit(parent=self.eventsTab)
        self.eventsOutputNameLineEdit.setText("")
        self.eventsOutputNameLineEdit.setObjectName("eventsOutputNameLineEdit")
        self.eventsGridLayout.addWidget(self.eventsOutputNameLineEdit, 14, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(parent=self.eventsTab)
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.eventsGridLayout.addWidget(self.line_3, 13, 0, 1, 2)
        self.eventsMeasureEndFieldCombo = QtWidgets.QComboBox(parent=self.eventsTab)
        self.eventsMeasureEndFieldCombo.setObjectName("eventsMeasureEndFieldCombo")
        self.eventsGridLayout.addWidget(self.eventsMeasureEndFieldCombo, 10, 1, 1, 1)
        self.eventsFeaturesSelectCombo = QtWidgets.QComboBox(parent=self.eventsTab)
        self.eventsFeaturesSelectCombo.setObjectName("eventsFeaturesSelectCombo")
        self.eventsGridLayout.addWidget(self.eventsFeaturesSelectCombo, 12, 1, 1, 1)
        self.eventsRouteFieldLabel = QtWidgets.QLabel(parent=self.eventsTab)
        self.eventsRouteFieldLabel.setObjectName("eventsRouteFieldLabel")
        self.eventsGridLayout.addWidget(self.eventsRouteFieldLabel, 7, 0, 1, 1)
        self.eventsLayerCombo = QtWidgets.QComboBox(parent=self.eventsTab)
        self.eventsLayerCombo.setObjectName("eventsLayerCombo")
        self.eventsGridLayout.addWidget(self.eventsLayerCombo, 6, 1, 1, 1)
        self.eventsFeaturesSelectLabel = QtWidgets.QLabel(parent=self.eventsTab)
        self.eventsFeaturesSelectLabel.setObjectName("eventsFeaturesSelectLabel")
        self.eventsGridLayout.addWidget(self.eventsFeaturesSelectLabel, 12, 0, 1, 1)
        self.eventsLrsRouteFieldLabel = QtWidgets.QLabel(parent=self.eventsTab)
        self.eventsLrsRouteFieldLabel.setObjectName("eventsLrsRouteFieldLabel")
        self.eventsGridLayout.addWidget(self.eventsLrsRouteFieldLabel, 4, 0, 1, 1)
        self.eventsMeasureStartFieldLabel = QtWidgets.QLabel(parent=self.eventsTab)
        self.eventsMeasureStartFieldLabel.setObjectName("eventsMeasureStartFieldLabel")
        self.eventsGridLayout.addWidget(self.eventsMeasureStartFieldLabel, 8, 0, 1, 1)
        self.line_8 = QtWidgets.QFrame(parent=self.eventsTab)
        self.line_8.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_8.setObjectName("line_8")
        self.eventsGridLayout.addWidget(self.line_8, 5, 0, 1, 2)
        self.eventsLrsLayerLabel = QtWidgets.QLabel(parent=self.eventsTab)
        self.eventsLrsLayerLabel.setObjectName("eventsLrsLayerLabel")
        self.eventsGridLayout.addWidget(self.eventsLrsLayerLabel, 1, 0, 1, 1)
        self.eventsMeasureStartFieldCombo = QtWidgets.QComboBox(parent=self.eventsTab)
        self.eventsMeasureStartFieldCombo.setObjectName("eventsMeasureStartFieldCombo")
        self.eventsGridLayout.addWidget(self.eventsMeasureStartFieldCombo, 8, 1, 1, 1)
        self.eventsOffsetEndFieldLabel = QtWidgets.QLabel(parent=self.eventsTab)
        self.eventsOffsetEndFieldLabel.setObjectName("eventsOffsetEndFieldLabel")
        self.eventsGridLayout.addWidget(self.eventsOffsetEndFieldLabel, 11, 0, 1, 1)
        self.eventsOffsetEndFieldCombo = QtWidgets.QComboBox(parent=self.eventsTab)
        self.eventsOffsetEndFieldCombo.setObjectName("eventsOffsetEndFieldCombo")
        self.eventsGridLayout.addWidget(self.eventsOffsetEndFieldCombo, 11, 1, 1, 1)
        self.eventsErrorFieldLabel = QtWidgets.QLabel(parent=self.eventsTab)
        self.eventsErrorFieldLabel.setObjectName("eventsErrorFieldLabel")
        self.eventsGridLayout.addWidget(self.eventsErrorFieldLabel, 15, 0, 1, 1)
        self.eventsRouteFieldCombo = QtWidgets.QComboBox(parent=self.eventsTab)
        self.eventsRouteFieldCombo.setObjectName("eventsRouteFieldCombo")
        self.eventsGridLayout.addWidget(self.eventsRouteFieldCombo, 7, 1, 1, 1)
        self.eventsOutputNameLabel = QtWidgets.QLabel(parent=self.eventsTab)
        self.eventsOutputNameLabel.setObjectName("eventsOutputNameLabel")
        self.eventsGridLayout.addWidget(self.eventsOutputNameLabel, 14, 0, 1, 1)
        self.eventsLayerLabel = QtWidgets.QLabel(parent=self.eventsTab)
        self.eventsLayerLabel.setObjectName("eventsLayerLabel")
        self.eventsGridLayout.addWidget(self.eventsLayerLabel, 6, 0, 1, 1)
        self.eventsLrsLayerCombo = QtWidgets.QComboBox(parent=self.eventsTab)
        self.eventsLrsLayerCombo.setObjectName("eventsLrsLayerCombo")
        self.eventsGridLayout.addWidget(self.eventsLrsLayerCombo, 1, 1, 1, 1)
        self.eventsOffsetStartFieldLabel = QtWidgets.QLabel(parent=self.eventsTab)
        self.eventsOffsetStartFieldLabel.setObjectName("eventsOffsetStartFieldLabel")
        self.eventsGridLayout.addWidget(self.eventsOffsetStartFieldLabel, 9, 0, 1, 1)
        self.eventsOffsetStartFieldCombo = QtWidgets.QComboBox(parent=self.eventsTab)
        self.eventsOffsetStartFieldCombo.setObjectName("eventsOffsetStartFieldCombo")
        self.eventsGridLayout.addWidget(self.eventsOffsetStartFieldCombo, 9, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.eventsGridLayout)
        self.eventsButtonBox = QtWidgets.QDialogButtonBox(parent=self.eventsTab)
        self.eventsButtonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Help
            | QtWidgets.QDialogButtonBox.StandardButton.Ok
            | QtWidgets.QDialogButtonBox.StandardButton.Reset
        )
        self.eventsButtonBox.setObjectName("eventsButtonBox")
        self.verticalLayout_4.addWidget(self.eventsButtonBox)
        self.eventsProgressBar = QtWidgets.QProgressBar(parent=self.eventsTab)
        self.eventsProgressBar.setProperty("value", 24)
        self.eventsProgressBar.setObjectName("eventsProgressBar")
        self.verticalLayout_4.addWidget(self.eventsProgressBar)
        spacerItem1 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.verticalLayout_4.addItem(spacerItem1)
        self.eventsButtonBox.raise_()
        self.eventsProgressBar.raise_()
        self.tabWidget.addTab(self.eventsTab, "")
        self.measureTab = QtWidgets.QWidget()
        self.measureTab.setObjectName("measureTab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.measureTab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.measureLayerLabel = QtWidgets.QLabel(parent=self.measureTab)
        self.measureLayerLabel.setObjectName("measureLayerLabel")
        self.gridLayout.addWidget(self.measureLayerLabel, 7, 0, 1, 1)
        self.measureOutputNameLabel = QtWidgets.QLabel(parent=self.measureTab)
        self.measureOutputNameLabel.setObjectName("measureOutputNameLabel")
        self.gridLayout.addWidget(self.measureOutputNameLabel, 13, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(parent=self.measureTab)
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 12, 0, 1, 2)
        self.measureOutputRouteFieldLabel = QtWidgets.QLabel(parent=self.measureTab)
        self.measureOutputRouteFieldLabel.setObjectName("measureOutputRouteFieldLabel")
        self.gridLayout.addWidget(self.measureOutputRouteFieldLabel, 14, 0, 1, 1)
        self.measureMeasureFieldLabel = QtWidgets.QLabel(parent=self.measureTab)
        self.measureMeasureFieldLabel.setObjectName("measureMeasureFieldLabel")
        self.gridLayout.addWidget(self.measureMeasureFieldLabel, 15, 0, 1, 1)
        self.measureThresholdLabel = QtWidgets.QLabel(parent=self.measureTab)
        self.measureThresholdLabel.setObjectName("measureThresholdLabel")
        self.gridLayout.addWidget(self.measureThresholdLabel, 10, 0, 1, 1)
        self.measureLrsLayerLabel = QtWidgets.QLabel(parent=self.measureTab)
        self.measureLrsLayerLabel.setObjectName("measureLrsLayerLabel")
        self.gridLayout.addWidget(self.measureLrsLayerLabel, 1, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(parent=self.measureTab)
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 9, 0, 1, 2)
        self.measureLrsRouteFieldLabel = QtWidgets.QLabel(parent=self.measureTab)
        self.measureLrsRouteFieldLabel.setObjectName("measureLrsRouteFieldLabel")
        self.gridLayout.addWidget(self.measureLrsRouteFieldLabel, 2, 0, 1, 1)
        self.line_9 = QtWidgets.QFrame(parent=self.measureTab)
        self.line_9.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout.addWidget(self.line_9, 4, 0, 1, 2)
        self.measureMeasureFieldLineEdit = QtWidgets.QLineEdit(parent=self.measureTab)
        self.measureMeasureFieldLineEdit.setText("")
        self.measureMeasureFieldLineEdit.setObjectName("measureMeasureFieldLineEdit")
        self.gridLayout.addWidget(self.measureMeasureFieldLineEdit, 15, 1, 1, 1)
        self.measureOutputRouteFieldLineEdit = QtWidgets.QLineEdit(
            parent=self.measureTab
        )
        self.measureOutputRouteFieldLineEdit.setText("")
        self.measureOutputRouteFieldLineEdit.setObjectName(
            "measureOutputRouteFieldLineEdit"
        )
        self.gridLayout.addWidget(self.measureOutputRouteFieldLineEdit, 14, 1, 1, 1)
        self.measureOutputNameLineEdit = QtWidgets.QLineEdit(parent=self.measureTab)
        self.measureOutputNameLineEdit.setText("")
        self.measureOutputNameLineEdit.setObjectName("measureOutputNameLineEdit")
        self.gridLayout.addWidget(self.measureOutputNameLineEdit, 13, 1, 1, 1)
        self.measureThresholdSpin = QtWidgets.QDoubleSpinBox(parent=self.measureTab)
        self.measureThresholdSpin.setDecimals(6)
        self.measureThresholdSpin.setMaximum(1000000.0)
        self.measureThresholdSpin.setProperty("value", 0.0)
        self.measureThresholdSpin.setObjectName("measureThresholdSpin")
        self.gridLayout.addWidget(self.measureThresholdSpin, 10, 1, 1, 1)
        self.measureLayerCombo = QtWidgets.QComboBox(parent=self.measureTab)
        self.measureLayerCombo.setObjectName("measureLayerCombo")
        self.gridLayout.addWidget(self.measureLayerCombo, 7, 1, 1, 1)
        self.measureLrsRouteFieldCombo = QtWidgets.QComboBox(parent=self.measureTab)
        self.measureLrsRouteFieldCombo.setObjectName("measureLrsRouteFieldCombo")
        self.gridLayout.addWidget(self.measureLrsRouteFieldCombo, 2, 1, 1, 1)
        self.measureLrsLayerCombo = QtWidgets.QComboBox(parent=self.measureTab)
        self.measureLrsLayerCombo.setObjectName("measureLrsLayerCombo")
        self.gridLayout.addWidget(self.measureLrsLayerCombo, 1, 1, 1, 1)
        self.measureRouteFieldLabel = QtWidgets.QLabel(parent=self.measureTab)
        self.measureRouteFieldLabel.setObjectName("measureRouteFieldLabel")
        self.gridLayout.addWidget(self.measureRouteFieldLabel, 8, 0, 1, 1)
        self.measureRouteFieldCombo = QtWidgets.QComboBox(parent=self.measureTab)
        self.measureRouteFieldCombo.setObjectName("measureRouteFieldCombo")
        self.gridLayout.addWidget(self.measureRouteFieldCombo, 8, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.measureButtonBox = QtWidgets.QDialogButtonBox(parent=self.measureTab)
        self.measureButtonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Help
            | QtWidgets.QDialogButtonBox.StandardButton.Ok
            | QtWidgets.QDialogButtonBox.StandardButton.Reset
        )
        self.measureButtonBox.setObjectName("measureButtonBox")
        self.verticalLayout_5.addWidget(self.measureButtonBox)
        self.measureProgressBar = QtWidgets.QProgressBar(parent=self.measureTab)
        self.measureProgressBar.setProperty("value", 24)
        self.measureProgressBar.setObjectName("measureProgressBar")
        self.verticalLayout_5.addWidget(self.measureProgressBar)
        spacerItem2 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.verticalLayout_5.addItem(spacerItem2)
        self.tabWidget.addTab(self.measureTab, "")
        self.genTab = QtWidgets.QWidget()
        self.genTab.setObjectName("genTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.genTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.calibTabWidget = QtWidgets.QTabWidget(parent=self.genTab)
        self.calibTabWidget.setObjectName("calibTabWidget")
        self.calibTab = QtWidgets.QWidget()
        self.calibTab.setObjectName("calibTab")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.calibTab)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.calibWidget = QtWidgets.QWidget(parent=self.calibTab)
        self.calibWidget.setObjectName("calibWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.calibWidget)
        self.verticalLayout_7.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.genGridLayout = QtWidgets.QGridLayout()
        self.genGridLayout.setObjectName("genGridLayout")
        self.line_2 = QtWidgets.QFrame(parent=self.calibWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.genGridLayout.addWidget(self.line_2, 9, 0, 1, 2)
        self.genThresholdSpin = QtWidgets.QDoubleSpinBox(parent=self.calibWidget)
        self.genThresholdSpin.setDecimals(6)
        self.genThresholdSpin.setMaximum(1000000.0)
        self.genThresholdSpin.setProperty("value", 0.0)
        self.genThresholdSpin.setObjectName("genThresholdSpin")
        self.genGridLayout.addWidget(self.genThresholdSpin, 15, 1, 1, 1)
        self.genSnapLabel = QtWidgets.QLabel(parent=self.calibWidget)
        self.genSnapLabel.setObjectName("genSnapLabel")
        self.genGridLayout.addWidget(self.genSnapLabel, 14, 0, 1, 1)
        self.genLineRouteFieldLabel = QtWidgets.QLabel(parent=self.calibWidget)
        self.genLineRouteFieldLabel.setObjectName("genLineRouteFieldLabel")
        self.genGridLayout.addWidget(self.genLineRouteFieldLabel, 1, 0, 1, 1)
        self.genMeasureUnitCombo = QtWidgets.QComboBox(parent=self.calibWidget)
        self.genMeasureUnitCombo.setObjectName("genMeasureUnitCombo")
        self.genGridLayout.addWidget(self.genMeasureUnitCombo, 6, 1, 1, 1)
        self.genExtrapolateLabel = QtWidgets.QLabel(parent=self.calibWidget)
        self.genExtrapolateLabel.setObjectName("genExtrapolateLabel")
        self.genGridLayout.addWidget(self.genExtrapolateLabel, 17, 0, 1, 1)
        self.genPointRouteFieldCombo = QtWidgets.QComboBox(parent=self.calibWidget)
        self.genPointRouteFieldCombo.setObjectName("genPointRouteFieldCombo")
        self.genGridLayout.addWidget(self.genPointRouteFieldCombo, 4, 1, 1, 1)
        self.genPointLayerCombo = QtWidgets.QComboBox(parent=self.calibWidget)
        self.genPointLayerCombo.setObjectName("genPointLayerCombo")
        self.genGridLayout.addWidget(self.genPointLayerCombo, 3, 1, 1, 1)
        self.genThresholdLabel = QtWidgets.QLabel(parent=self.calibWidget)
        self.genThresholdLabel.setObjectName("genThresholdLabel")
        self.genGridLayout.addWidget(self.genThresholdLabel, 15, 0, 1, 1)
        self.genPointRouteFieldLabel = QtWidgets.QLabel(parent=self.calibWidget)
        self.genPointRouteFieldLabel.setObjectName("genPointRouteFieldLabel")
        self.genGridLayout.addWidget(self.genPointRouteFieldLabel, 4, 0, 1, 1)
        self.genSelectionModeCombo = QtWidgets.QComboBox(parent=self.calibWidget)
        self.genSelectionModeCombo.setObjectName("genSelectionModeCombo")
        self.genGridLayout.addWidget(self.genSelectionModeCombo, 13, 0, 1, 1)
        self.genSnapSpin = QtWidgets.QDoubleSpinBox(parent=self.calibWidget)
        self.genSnapSpin.setDecimals(6)
        self.genSnapSpin.setMaximum(1000000.0)
        self.genSnapSpin.setObjectName("genSnapSpin")
        self.genGridLayout.addWidget(self.genSnapSpin, 14, 1, 1, 1)
        self.genPointMeasureFieldCombo = QtWidgets.QComboBox(parent=self.calibWidget)
        self.genPointMeasureFieldCombo.setObjectName("genPointMeasureFieldCombo")
        self.genGridLayout.addWidget(self.genPointMeasureFieldCombo, 5, 1, 1, 1)
        self.genLineLayerCombo = QtWidgets.QComboBox(parent=self.calibWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.genLineLayerCombo.sizePolicy().hasHeightForWidth()
        )
        self.genLineLayerCombo.setSizePolicy(sizePolicy)
        self.genLineLayerCombo.setObjectName("genLineLayerCombo")
        self.genGridLayout.addWidget(self.genLineLayerCombo, 0, 1, 1, 1)
        self.genLineLayerLabel = QtWidgets.QLabel(parent=self.calibWidget)
        self.genLineLayerLabel.setObjectName("genLineLayerLabel")
        self.genGridLayout.addWidget(self.genLineLayerLabel, 0, 0, 1, 1)
        self.genLineRouteFieldCombo = QtWidgets.QComboBox(parent=self.calibWidget)
        self.genLineRouteFieldCombo.setObjectName("genLineRouteFieldCombo")
        self.genGridLayout.addWidget(self.genLineRouteFieldCombo, 1, 1, 1, 1)
        self.genPointMeasureFieldLabel = QtWidgets.QLabel(parent=self.calibWidget)
        self.genPointMeasureFieldLabel.setObjectName("genPointMeasureFieldLabel")
        self.genGridLayout.addWidget(self.genPointMeasureFieldLabel, 5, 0, 1, 1)
        self.genParallelModeLabel = QtWidgets.QLabel(parent=self.calibWidget)
        self.genParallelModeLabel.setObjectName("genParallelModeLabel")
        self.genGridLayout.addWidget(self.genParallelModeLabel, 16, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.genSelectionLineEdit = QtWidgets.QLineEdit(parent=self.calibWidget)
        self.genSelectionLineEdit.setObjectName("genSelectionLineEdit")
        self.horizontalLayout.addWidget(self.genSelectionLineEdit)
        self.genSelectionButton = QtWidgets.QPushButton(parent=self.calibWidget)
        self.genSelectionButton.setObjectName("genSelectionButton")
        self.horizontalLayout.addWidget(self.genSelectionButton)
        self.genGridLayout.addLayout(self.horizontalLayout, 13, 1, 1, 1)
        self.line = QtWidgets.QFrame(parent=self.calibWidget)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.genGridLayout.addWidget(self.line, 2, 0, 1, 2)
        self.genParallelModeCombo = QtWidgets.QComboBox(parent=self.calibWidget)
        self.genParallelModeCombo.setObjectName("genParallelModeCombo")
        self.genGridLayout.addWidget(self.genParallelModeCombo, 16, 1, 1, 1)
        self.genPointLayerLabel = QtWidgets.QLabel(parent=self.calibWidget)
        self.genPointLayerLabel.setObjectName("genPointLayerLabel")
        self.genGridLayout.addWidget(self.genPointLayerLabel, 3, 0, 1, 1)
        self.genExtrapolateCheckBox = QtWidgets.QCheckBox(parent=self.calibWidget)
        self.genExtrapolateCheckBox.setText("")
        self.genExtrapolateCheckBox.setObjectName("genExtrapolateCheckBox")
        self.genGridLayout.addWidget(self.genExtrapolateCheckBox, 17, 1, 1, 1)
        self.genMeasureUnitLabel = QtWidgets.QLabel(parent=self.calibWidget)
        self.genMeasureUnitLabel.setObjectName("genMeasureUnitLabel")
        self.genGridLayout.addWidget(self.genMeasureUnitLabel, 6, 0, 1, 1)
        self.verticalLayout_7.addLayout(self.genGridLayout)
        self.genButtonBox = QtWidgets.QDialogButtonBox(parent=self.calibWidget)
        self.genButtonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Help
            | QtWidgets.QDialogButtonBox.StandardButton.Ok
            | QtWidgets.QDialogButtonBox.StandardButton.Reset
        )
        self.genButtonBox.setObjectName("genButtonBox")
        self.verticalLayout_7.addWidget(self.genButtonBox)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.genOutputNameLabel = QtWidgets.QLabel(parent=self.calibWidget)
        self.genOutputNameLabel.setObjectName("genOutputNameLabel")
        self.horizontalLayout_6.addWidget(self.genOutputNameLabel)
        self.genOutputNameLineEdit = QtWidgets.QLineEdit(parent=self.calibWidget)
        self.genOutputNameLineEdit.setText("")
        self.genOutputNameLineEdit.setObjectName("genOutputNameLineEdit")
        self.horizontalLayout_6.addWidget(self.genOutputNameLineEdit)
        self.genCreateOutputButton = QtWidgets.QPushButton(parent=self.calibWidget)
        self.genCreateOutputButton.setObjectName("genCreateOutputButton")
        self.horizontalLayout_6.addWidget(self.genCreateOutputButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.genProgressFrame = QtWidgets.QFrame(parent=self.calibWidget)
        self.genProgressFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.genProgressFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.genProgressFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.genProgressFrame.setLineWidth(0)
        self.genProgressFrame.setObjectName("genProgressFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.genProgressFrame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.genProgressLabel = QtWidgets.QLabel(parent=self.genProgressFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.genProgressLabel.sizePolicy().hasHeightForWidth()
        )
        self.genProgressLabel.setSizePolicy(sizePolicy)
        self.genProgressLabel.setObjectName("genProgressLabel")
        self.horizontalLayout_3.addWidget(self.genProgressLabel)
        self.genProgressBar = QtWidgets.QProgressBar(parent=self.genProgressFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.genProgressBar.sizePolicy().hasHeightForWidth()
        )
        self.genProgressBar.setSizePolicy(sizePolicy)
        self.genProgressBar.setProperty("value", 24)
        self.genProgressBar.setObjectName("genProgressBar")
        self.horizontalLayout_3.addWidget(self.genProgressBar)
        self.verticalLayout_7.addWidget(self.genProgressFrame)
        spacerItem3 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.verticalLayout_7.addItem(spacerItem3)
        self.verticalLayout_10.addWidget(self.calibWidget)
        self.calibTabWidget.addTab(self.calibTab, "")
        self.errorTab = QtWidgets.QWidget()
        self.errorTab.setObjectName("errorTab")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.errorTab)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.errorWidget = QtWidgets.QWidget(parent=self.errorTab)
        self.errorWidget.setObjectName("errorWidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.errorWidget)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_4.setSpacing(8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.errorFilterLabel = QtWidgets.QLabel(parent=self.errorWidget)
        self.errorFilterLabel.setObjectName("errorFilterLabel")
        self.horizontalLayout_4.addWidget(self.errorFilterLabel)
        self.errorFilterLineEdit = QtWidgets.QLineEdit(parent=self.errorWidget)
        self.errorFilterLineEdit.setObjectName("errorFilterLineEdit")
        self.horizontalLayout_4.addWidget(self.errorFilterLineEdit)
        self.verticalLayout_9.addLayout(self.horizontalLayout_4)
        self.errorView = QtWidgets.QTableView(parent=self.errorWidget)
        self.errorView.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.SingleSelection
        )
        self.errorView.setSelectionBehavior(
            QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows
        )
        self.errorView.setSortingEnabled(True)
        self.errorView.setObjectName("errorView")
        self.errorView.verticalHeader().setVisible(False)
        self.errorView.verticalHeader().setDefaultSectionSize(20)
        self.verticalLayout_9.addWidget(self.errorView)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(8, 8, 8, 8)
        self.gridLayout_4.setVerticalSpacing(8)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.errorTotalLength = QtWidgets.QLabel(parent=self.errorWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.errorTotalLength.sizePolicy().hasHeightForWidth()
        )
        self.errorTotalLength.setSizePolicy(sizePolicy)
        self.errorTotalLength.setObjectName("errorTotalLength")
        self.gridLayout_4.addWidget(self.errorTotalLength, 0, 2, 1, 1)
        self.errorIncludedLengthLabel = QtWidgets.QLabel(parent=self.errorWidget)
        self.errorIncludedLengthLabel.setObjectName("errorIncludedLengthLabel")
        self.gridLayout_4.addWidget(self.errorIncludedLengthLabel, 1, 0, 1, 1)
        self.errorSuccessLengthLabel = QtWidgets.QLabel(parent=self.errorWidget)
        self.errorSuccessLengthLabel.setObjectName("errorSuccessLengthLabel")
        self.gridLayout_4.addWidget(self.errorSuccessLengthLabel, 2, 0, 1, 1)
        self.errorSuccessLength = QtWidgets.QLabel(parent=self.errorWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.errorSuccessLength.sizePolicy().hasHeightForWidth()
        )
        self.errorSuccessLength.setSizePolicy(sizePolicy)
        self.errorSuccessLength.setObjectName("errorSuccessLength")
        self.gridLayout_4.addWidget(self.errorSuccessLength, 2, 2, 1, 1)
        self.errorTotalLengthLabel = QtWidgets.QLabel(parent=self.errorWidget)
        self.errorTotalLengthLabel.setObjectName("errorTotalLengthLabel")
        self.gridLayout_4.addWidget(self.errorTotalLengthLabel, 0, 0, 1, 1)
        self.errorIncludedLength = QtWidgets.QLabel(parent=self.errorWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.errorIncludedLength.sizePolicy().hasHeightForWidth()
        )
        self.errorIncludedLength.setSizePolicy(sizePolicy)
        self.errorIncludedLength.setObjectName("errorIncludedLength")
        self.gridLayout_4.addWidget(self.errorIncludedLength, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.errorWidget)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.errorWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.errorWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 2, 1, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.errorButtonBox = QtWidgets.QDialogButtonBox(parent=self.errorWidget)
        self.errorButtonBox.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.errorButtonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Help
        )
        self.errorButtonBox.setObjectName("errorButtonBox")
        self.horizontalLayout_2.addWidget(self.errorButtonBox)
        spacerItem4 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_2.addItem(spacerItem4)
        self.errorZoomButton = QtWidgets.QToolButton(parent=self.errorWidget)
        self.errorZoomButton.setToolButtonStyle(
            QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon
        )
        self.errorZoomButton.setObjectName("errorZoomButton")
        self.horizontalLayout_2.addWidget(self.errorZoomButton)
        self.addErrorLayersButton = QtWidgets.QPushButton(parent=self.errorWidget)
        self.addErrorLayersButton.setObjectName("addErrorLayersButton")
        self.horizontalLayout_2.addWidget(self.addErrorLayersButton)
        self.addQualityLayerButton = QtWidgets.QPushButton(parent=self.errorWidget)
        self.addQualityLayerButton.setObjectName("addQualityLayerButton")
        self.horizontalLayout_2.addWidget(self.addQualityLayerButton)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.verticalLayout_11.addWidget(self.errorWidget)
        self.calibTabWidget.addTab(self.errorTab, "")
        self.verticalLayout_2.addWidget(self.calibTabWidget)
        self.tabWidget.addTab(self.genTab, "")
        self.helpTab = QtWidgets.QWidget()
        self.helpTab.setObjectName("helpTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.helpTab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.helpLayout = QtWidgets.QVBoxLayout()
        self.helpLayout.setObjectName("helpLayout")
        self.helpTextBrowser = QtWidgets.QTextBrowser(parent=self.helpTab)
        self.helpTextBrowser.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.helpTextBrowser.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.helpTextBrowser.setLineWidth(0)
        self.helpTextBrowser.setObjectName("helpTextBrowser")
        self.helpLayout.addWidget(self.helpTextBrowser)
        self.verticalLayout_3.addLayout(self.helpLayout)
        self.tabWidget.addTab(self.helpTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        LrsDockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(LrsDockWidget)
        self.tabWidget.setCurrentIndex(0)
        self.calibTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LrsDockWidget)
        LrsDockWidget.setTabOrder(self.tabWidget, self.locateLrsLayerCombo)
        LrsDockWidget.setTabOrder(
            self.locateLrsLayerCombo, self.locateLrsRouteFieldCombo
        )
        LrsDockWidget.setTabOrder(self.locateLrsRouteFieldCombo, self.locateRouteCombo)
        LrsDockWidget.setTabOrder(self.locateRouteCombo, self.locateMeasureSpin)
        LrsDockWidget.setTabOrder(self.locateMeasureSpin, self.locateHighlightCheckBox)
        LrsDockWidget.setTabOrder(self.locateHighlightCheckBox, self.locateBufferSpin)
        LrsDockWidget.setTabOrder(self.locateBufferSpin, self.locateHelpButton)
        LrsDockWidget.setTabOrder(self.locateHelpButton, self.locateCenterButton)
        LrsDockWidget.setTabOrder(self.locateCenterButton, self.locateZoomButton)
        LrsDockWidget.setTabOrder(self.locateZoomButton, self.eventsLrsLayerCombo)
        LrsDockWidget.setTabOrder(
            self.eventsLrsLayerCombo, self.eventsLrsRouteFieldCombo
        )
        LrsDockWidget.setTabOrder(self.eventsLrsRouteFieldCombo, self.eventsLayerCombo)
        LrsDockWidget.setTabOrder(self.eventsLayerCombo, self.eventsRouteFieldCombo)
        LrsDockWidget.setTabOrder(
            self.eventsRouteFieldCombo, self.eventsMeasureStartFieldCombo
        )
        LrsDockWidget.setTabOrder(
            self.eventsMeasureStartFieldCombo, self.eventsMeasureEndFieldCombo
        )
        LrsDockWidget.setTabOrder(
            self.eventsMeasureEndFieldCombo, self.eventsFeaturesSelectCombo
        )
        LrsDockWidget.setTabOrder(
            self.eventsFeaturesSelectCombo, self.eventsOutputNameLineEdit
        )
        LrsDockWidget.setTabOrder(
            self.eventsOutputNameLineEdit, self.eventsErrorFieldLineEdit
        )
        LrsDockWidget.setTabOrder(
            self.eventsErrorFieldLineEdit, self.measureLrsLayerCombo
        )
        LrsDockWidget.setTabOrder(
            self.measureLrsLayerCombo, self.measureLrsRouteFieldCombo
        )
        LrsDockWidget.setTabOrder(
            self.measureLrsRouteFieldCombo, self.measureLayerCombo
        )
        LrsDockWidget.setTabOrder(self.measureLayerCombo, self.measureRouteFieldCombo)
        LrsDockWidget.setTabOrder(
            self.measureRouteFieldCombo, self.measureThresholdSpin
        )
        LrsDockWidget.setTabOrder(
            self.measureThresholdSpin, self.measureOutputNameLineEdit
        )
        LrsDockWidget.setTabOrder(
            self.measureOutputNameLineEdit, self.measureOutputRouteFieldLineEdit
        )
        LrsDockWidget.setTabOrder(
            self.measureOutputRouteFieldLineEdit, self.measureMeasureFieldLineEdit
        )
        LrsDockWidget.setTabOrder(self.measureMeasureFieldLineEdit, self.calibTabWidget)
        LrsDockWidget.setTabOrder(self.calibTabWidget, self.genLineLayerCombo)
        LrsDockWidget.setTabOrder(self.genLineLayerCombo, self.genLineRouteFieldCombo)
        LrsDockWidget.setTabOrder(self.genLineRouteFieldCombo, self.genPointLayerCombo)
        LrsDockWidget.setTabOrder(self.genPointLayerCombo, self.genPointRouteFieldCombo)
        LrsDockWidget.setTabOrder(
            self.genPointRouteFieldCombo, self.genPointMeasureFieldCombo
        )
        LrsDockWidget.setTabOrder(
            self.genPointMeasureFieldCombo, self.genMeasureUnitCombo
        )
        LrsDockWidget.setTabOrder(self.genMeasureUnitCombo, self.genSelectionModeCombo)
        LrsDockWidget.setTabOrder(self.genSelectionModeCombo, self.genSelectionLineEdit)
        LrsDockWidget.setTabOrder(self.genSelectionLineEdit, self.genSelectionButton)
        LrsDockWidget.setTabOrder(self.genSelectionButton, self.genSnapSpin)
        LrsDockWidget.setTabOrder(self.genSnapSpin, self.genThresholdSpin)
        LrsDockWidget.setTabOrder(self.genThresholdSpin, self.genParallelModeCombo)
        LrsDockWidget.setTabOrder(
            self.genParallelModeCombo, self.genExtrapolateCheckBox
        )
        LrsDockWidget.setTabOrder(self.genExtrapolateCheckBox, self.genButtonBox)
        LrsDockWidget.setTabOrder(self.genButtonBox, self.genOutputNameLineEdit)
        LrsDockWidget.setTabOrder(
            self.genOutputNameLineEdit, self.genCreateOutputButton
        )
        LrsDockWidget.setTabOrder(self.genCreateOutputButton, self.errorFilterLineEdit)
        LrsDockWidget.setTabOrder(self.errorFilterLineEdit, self.errorView)
        LrsDockWidget.setTabOrder(self.errorView, self.errorButtonBox)
        LrsDockWidget.setTabOrder(self.errorButtonBox, self.errorZoomButton)
        LrsDockWidget.setTabOrder(self.errorZoomButton, self.addErrorLayersButton)
        LrsDockWidget.setTabOrder(self.addErrorLayersButton, self.addQualityLayerButton)
        LrsDockWidget.setTabOrder(self.addQualityLayerButton, self.helpTextBrowser)

    def retranslateUi(self, LrsDockWidget):
        _translate = QtCore.QCoreApplication.translate
        LrsDockWidget.setWindowTitle(_translate("LrsDockWidget", "&LRS"))
        self.locateLrsRouteFieldLabel.setText(
            _translate("LrsDockWidget", "Route field")
        )
        self.locateCoordinates.setText(_translate("LrsDockWidget", "<coordinates>"))
        self.locateCoordinatesLabel.setText(_translate("LrsDockWidget", "Coordinates"))
        self.locateMeasureLabel.setText(_translate("LrsDockWidget", "Measure"))
        self.locateBufferSpin.setToolTip(
            _translate(
                "LrsDockWidget", "Buffer around event in map units used for zoom."
            )
        )
        self.locateRanges.setText(_translate("LrsDockWidget", "<measures>"))
        self.locateLrsLayerLabel.setText(
            _translate("LrsDockWidget", "Layer with measures")
        )
        self.locateRouteLabel.setText(_translate("LrsDockWidget", "Route"))
        self.locateRangesLabel.setText(
            _translate("LrsDockWidget", "Available measures")
        )
        self.locateBufferLabel.setToolTip(
            _translate(
                "LrsDockWidget", "Buffer around event in map units used for zoom."
            )
        )
        self.locateBufferLabel.setText(_translate("LrsDockWidget", "Zoom buffer"))
        self.locateHighlightLabel.setText(_translate("LrsDockWidget", "Highlight"))
        self.locateHelpButton.setText(_translate("LrsDockWidget", "Help"))
        self.locateCenterButton.setText(_translate("LrsDockWidget", "Center"))
        self.locateZoomButton.setText(_translate("LrsDockWidget", "Zoom"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.locateTab),
            _translate("LrsDockWidget", "Locate"),
        )
        self.eventsMeasureEndFieldLabel.setToolTip(
            _translate(
                "LrsDockWidget", "End of linear event. Leave blank for punctual events."
            )
        )
        self.eventsMeasureEndFieldLabel.setText(
            _translate("LrsDockWidget", "End measure field")
        )
        self.eventsMeasureEndFieldCombo.setToolTip(
            _translate(
                "LrsDockWidget", "End of linear event. Leave blank for punctual events."
            )
        )
        self.eventsRouteFieldLabel.setText(
            _translate("LrsDockWidget", "Events route field")
        )
        self.eventsFeaturesSelectLabel.setText(_translate("LrsDockWidget", "Features"))
        self.eventsLrsRouteFieldLabel.setText(
            _translate("LrsDockWidget", "Route field")
        )
        self.eventsMeasureStartFieldLabel.setToolTip(
            _translate("LrsDockWidget", "Measure of punctual or start of linear event.")
        )
        self.eventsMeasureStartFieldLabel.setText(
            _translate("LrsDockWidget", "Start measure field")
        )
        self.eventsLrsLayerLabel.setText(
            _translate("LrsDockWidget", "Layer with measures")
        )
        self.eventsMeasureStartFieldCombo.setToolTip(
            _translate("LrsDockWidget", "Measure of punctual or start of linear event.")
        )
        self.eventsOffsetEndFieldLabel.setText(
            _translate("LrsDockWidget", "End offset field")
        )
        self.eventsErrorFieldLabel.setText(
            _translate("LrsDockWidget", "Output error field")
        )
        self.eventsOutputNameLabel.setText(
            _translate("LrsDockWidget", "Output layer name")
        )
        self.eventsLayerLabel.setText(_translate("LrsDockWidget", "Events layer"))
        self.eventsOffsetStartFieldLabel.setText(
            _translate("LrsDockWidget", "Start offset field")
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.eventsTab),
            _translate("LrsDockWidget", "Events"),
        )
        self.measureLayerLabel.setText(_translate("LrsDockWidget", "Layer"))
        self.measureOutputNameLabel.setText(
            _translate("LrsDockWidget", "Output layer name")
        )
        self.measureOutputRouteFieldLabel.setText(
            _translate("LrsDockWidget", "Output route field")
        )
        self.measureMeasureFieldLabel.setText(
            _translate("LrsDockWidget", "Output measure field")
        )
        self.measureThresholdLabel.setToolTip(
            _translate("LrsDockWidget", "Maximum distance of point from line.")
        )
        self.measureThresholdLabel.setText(
            _translate("LrsDockWidget", "Max point distance")
        )
        self.measureLrsLayerLabel.setText(
            _translate("LrsDockWidget", "Layer with measures")
        )
        self.measureLrsRouteFieldLabel.setText(
            _translate("LrsDockWidget", "Route field")
        )
        self.measureThresholdSpin.setToolTip(
            _translate("LrsDockWidget", "Maximum distance of point from line.")
        )
        self.measureRouteFieldLabel.setText(
            _translate("LrsDockWidget", "Route field (optional)")
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.measureTab),
            _translate("LrsDockWidget", "Measures"),
        )
        self.genThresholdSpin.setToolTip(
            _translate("LrsDockWidget", "Maximum distance of point from line.")
        )
        self.genSnapLabel.setToolTip(
            _translate("LrsDockWidget", "Maximum gap between lies to be snapped.")
        )
        self.genSnapLabel.setText(_translate("LrsDockWidget", "Max lines snap"))
        self.genLineRouteFieldLabel.setText(
            _translate("LrsDockWidget", "Lines route field")
        )
        self.genExtrapolateLabel.setToolTip(
            _translate(
                "LrsDockWidget", "Extrapolate before and after calibration points."
            )
        )
        self.genExtrapolateLabel.setText(_translate("LrsDockWidget", "Extrapolate"))
        self.genThresholdLabel.setToolTip(
            _translate("LrsDockWidget", "Maximum distance of point from line.")
        )
        self.genThresholdLabel.setText(
            _translate("LrsDockWidget", "Max point distance")
        )
        self.genPointRouteFieldLabel.setText(
            _translate("LrsDockWidget", "Points route field")
        )
        self.genSelectionModeCombo.setToolTip(
            _translate("LrsDockWidget", "Routes selection mode.")
        )
        self.genSnapSpin.setToolTip(
            _translate("LrsDockWidget", "Maximum gap between lies to be snapped.")
        )
        self.genLineLayerLabel.setText(_translate("LrsDockWidget", "Lines layer"))
        self.genPointMeasureFieldLabel.setText(
            _translate("LrsDockWidget", "Measure field")
        )
        self.genParallelModeLabel.setText(_translate("LrsDockWidget", "Parallels"))
        self.genSelectionLineEdit.setToolTip(
            _translate(
                "LrsDockWidget", "Comma separated list of routes to include/exclude."
            )
        )
        self.genSelectionButton.setText(_translate("LrsDockWidget", "Select"))
        self.genPointLayerLabel.setText(_translate("LrsDockWidget", "Points layer"))
        self.genExtrapolateCheckBox.setToolTip(
            _translate(
                "LrsDockWidget", "Extrapolate before and after calibration points."
            )
        )
        self.genMeasureUnitLabel.setToolTip(
            _translate(
                "LrsDockWidget",
                "<html><head/><body><p>Map units per measure unit.</p></body></html>",
            )
        )
        self.genMeasureUnitLabel.setText(_translate("LrsDockWidget", "Measure unit"))
        self.genOutputNameLabel.setText(
            _translate("LrsDockWidget", "Output layer name")
        )
        self.genCreateOutputButton.setText(_translate("LrsDockWidget", "Create"))
        self.genProgressLabel.setText(_translate("LrsDockWidget", "Progress label"))
        self.calibTabWidget.setTabText(
            self.calibTabWidget.indexOf(self.calibTab),
            _translate("LrsDockWidget", "Input"),
        )
        self.errorFilterLabel.setText(_translate("LrsDockWidget", "Filter"))
        self.errorTotalLength.setText(_translate("LrsDockWidget", "0.0"))
        self.errorIncludedLengthLabel.setText(
            _translate("LrsDockWidget", "Length of included lines")
        )
        self.errorSuccessLengthLabel.setText(
            _translate("LrsDockWidget", "Length of successfully created LRS")
        )
        self.errorSuccessLength.setText(_translate("LrsDockWidget", "0.0"))
        self.errorTotalLengthLabel.setText(
            _translate("LrsDockWidget", "Total length of all lines")
        )
        self.errorIncludedLength.setText(_translate("LrsDockWidget", "0.0"))
        self.label.setText(_translate("LrsDockWidget", " : "))
        self.label_2.setText(_translate("LrsDockWidget", " : "))
        self.label_3.setText(_translate("LrsDockWidget", " : "))
        self.errorZoomButton.setText(_translate("LrsDockWidget", "Zoom"))
        self.addErrorLayersButton.setToolTip(
            _translate("LrsDockWidget", "Add layers of errors to map view")
        )
        self.addErrorLayersButton.setText(
            _translate("LrsDockWidget", "Create error layers")
        )
        self.addQualityLayerButton.setToolTip(
            _translate("LrsDockWidget", "Add quality layer to map view")
        )
        self.addQualityLayerButton.setText(
            _translate("LrsDockWidget", "Create quality layer")
        )
        self.calibTabWidget.setTabText(
            self.calibTabWidget.indexOf(self.errorTab),
            _translate("LrsDockWidget", "Errors"),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.genTab),
            _translate("LrsDockWidget", "Calibration"),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.helpTab), _translate("LrsDockWidget", "Help")
        )
