# Form implementation generated from reading ui file 'c:\Users\FabianSchÃ¶pflin\sources\DBREF\InfraLRS\lrs\ui\ui_selectiondialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from qgis.PyQt import QtCore, QtWidgets


class Ui_LrsSelectionDialog(object):
    def setupUi(self, LrsSelectionDialog):
        LrsSelectionDialog.setObjectName("LrsSelectionDialog")
        LrsSelectionDialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(LrsSelectionDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(parent=LrsSelectionDialog)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.verticalHeader().setDefaultSectionSize(20)
        self.verticalLayout.addWidget(self.tableWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=LrsSelectionDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Cancel
            | QtWidgets.QDialogButtonBox.StandardButton.Ok
        )
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(LrsSelectionDialog)
        self.buttonBox.accepted.connect(LrsSelectionDialog.accept)  # type: ignore
        self.buttonBox.rejected.connect(LrsSelectionDialog.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LrsSelectionDialog)

    def retranslateUi(self, LrsSelectionDialog):
        _translate = QtCore.QCoreApplication.translate
        LrsSelectionDialog.setWindowTitle(
            _translate("LrsSelectionDialog", "LRS - routes selection")
        )
